### ISSUE TITLE
What is about AnonymizeIP?

### ISSUE THREAD

**Issue by ITforHome** [sergiodxa/next-ga#12]
Hi,
thank your for this component to use Google Analytics easily in my NextJS App. I come frome Germany and data protection is taken very seriously here. Hence the question: How can I use AnonymizeIP with your component?

Thanks for your answer and for your help

**Comment by sergiodxa** [comment]
I have no idea what is AnonymizeIP, this HOC just use react-ga under the hood and hook it to Next.js route events.

I recommend you to check how to do it with react-ga, in which case you may be able to do it with this module.

**Comment by sergiodxa** [comment]
I just read about it, I think since `ga` is a global module you should be able to use `window.ga` on a componentDidMount to enable AnonymizeIP.

**Comment by jgillich** [comment]
The solution would normally be this:
```
import ReactGA from 'react-ga'
ReactGA.set({ anonymizeIp: true })

```
BUT ReactGA.initialize must be called first, and next-ga will [instantly log a pageview](https://github.com/sergiodxa/next-ga/blob/2576cfe3d332427462197ec4aca010975fdb235c/src/index.js#L26) after initialization, and therefore include the full IP address.

**Comment by chibicode** [comment]
@sergiodxa Allowing more init options (like this PR https://github.com/sergiodxa/next-ga/pull/25) would solve the problem outlined by @jgillich.
