### ISSUE TITLE
not work with ie11

### ISSUE THREAD

**Issue by superbull** [sergiodxa/next-ga#22]
IE11 will report **syntax error** in `_app.js`

**Comment by petertenhoor** [comment]
Can confirm that the package doesn't work with IE11. There is an ES6 arrow function in browser.js on line 157.

**Comment by daright** [comment]
confirmed

**Comment by joaoahmad** [comment]
As a workaround, you can add `debug` package to your project

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
