### ISSUE TITLE
Custom dimensions

### ISSUE THREAD

**Issue by fgatti675** [sergiodxa/next-ga#30]
Hi, any chance you can integrate GA custom dimensions?

**Comment by doaboa** [comment]
+1 
I had to stop using this library because I can't track a click or programmatically track a pageview.

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
