### ISSUE TITLE
Query string not being submitted to google analytics

### ISSUE THREAD

**Issue by justin-prather** [sergiodxa/next-ga#31]
Would it be possible to add the query string to the url submitted to GA? specifically in https://github.com/sergiodxa/next-ga/blob/32899e9635efe1491a5f47469b0bd2250e496f99/src/analytics/prod.js#L13

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
