### ISSUE TITLE
Next.js 9 compatibility

### ISSUE THREAD

**Issue by connorzg** [sergiodxa/next-ga#38]
Seeing the following warning for this module. 
`warning " > next-ga@2.3.4" has incorrect peer dependency "next@^6.0.0 || ^7.0.0".`

Could you verify compatibility with next 9, and if properly functional update the peerDeps?

**Comment by leerob** [comment]
Another thing to note. Because of the `withGA` HOC, you will get this error.

```
Warning: You have opted-out of Automatic Prerendering due to getInitialProps in `pages/_app`
```

**Comment by olgn** [comment]
@leerob I've added this to _app.js - and because there is no need for a getInitialProps in `pages/_app` I don't get that error. Here is my _app.js

```
import React from 'react'
import App from 'next/app'
import Router from 'next/router'
import withGA from 'next-ga'

class MyApp extends App {
  // Only uncomment this method if you have blocking data requirements for
  // every single page in your application. This disables the ability to
  // perform automatic static optimization, causing every page in your app to
  // be server-side rendered.
  //
  // static async getInitialProps(appContext) {
  //   // calls page's `getInitialProps` and fills `appProps.pageProps`
  //   const appProps = await App.getInitialProps(appContext);
  //
  //   return { ...appProps }
  // }

  render() {
    const { Component, pageProps } = this.props
    return <Component {...pageProps} />
  }
}

export default withGA('<ga code>', Router)(MyApp)
```

**Comment by leerob** [comment]
Could you share the output from `next build` where it's saying those a pre-rendered pages? I wasn't able to get static pre-rendering working untill I moved `withGA` to `_document`.

**Comment by olgn** [comment]
ah you are correct, can confirm it will build i dont get static pre-rendering.

**Comment by timothymiller** [comment]
Moving the withGA call to _document from _app for Next.js 9 seems to be the current workaround. Works for me too.

**Comment by akx** [comment]
Moving the `withGA()` wrapping around the document component like https://github.com/leerob/leerob.io/pull/110 is doing results in

```
Error occurred prerendering page: TypeError: Document.renderDocument is not a function
```

for me (Next 9.1.2). 

😞

**Comment by semyou** [comment]
I confirm @akx I am having the same problem as you when I pass the withGA on _Document

**Comment by semyou** [comment]
@sergiodxa - Is there any way to allow my app to continue to use Automatic Prerendering?

**Comment by leerob** [comment]
Next has released [next-plugin-google-analytics](https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics) (still in beta) to provide a first-class plugin for this. 

Once it lands in `canary`, we should be able to utilize that package alongside Next 9.

https://github.com/zeit/next.js/issues/9314

**Comment by akx** [comment]
For the time being, I switched to using `react-ga` manually: https://github.com/koodiklinikka/koodiklinikka.fi/pull/55/commits/e27c50601d728b3b20320ffcc021a81657d8d4d6#diff-664264179f734c3055eba103c71ad479

**Comment by KolbySisk** [comment]
@akx You're using `componentDidMount` in `_Document`, which doesn't get included in the client.

I ended up doing this:

In your head:

```
{/* Global Site Tag (gtag.js) - Google Analytics */}
<script async src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE-ID}`} />
<script
  dangerouslySetInnerHTML={{
    __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '${GOOGLE-ID}', {
    page_path: window.location.pathname,
  });
`,
  }}
/>
```

In your _app.js:

```
// Google analytics event
Router.events.on('routeChangeComplete', url => {
  // @ts-ignore
  window.gtag('config', '${GOOGLE-ID}', {
    page_path: url,
  });
});
```

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
