### ISSUE TITLE
Provide option to track in dev mode

### ISSUE THREAD

**Issue by rohan-deshpande** [sergiodxa/next-ga#39]
I think that not tracking requests from localhost is a good default, but I also think we should be able to enable this via an argument because it's useful for testing prior to deploying to production. 

Right now I can't actually confirm that this works locally unless I deploy my app to a remote server which is not ideal. 

Would be happy to submit a PR for this.

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
