### ISSUE TITLE
Add "label" to event-tracking. 

### ISSUE THREAD

**Issue by malthemilthers** [sergiodxa/next-ga#41]
Hi, is there anyway we could add the label for events? Right now only "category" and "action" is used from the React.ga library. Would be great if we could add label as well? Shouldnt be that complicated since React.ga already supports it?

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
