### ISSUE TITLE
Should be able to use ReactGA plugins

### ISSUE THREAD

**Issue by richardkeller411** [sergiodxa/next-ga#43]
For Example.

// require the correct plugin
ReactGA.plugin.require('ec') //  'ecommerce'

// use that plugin in your other calls, e.g.:
ReactGA.plugin.execute('ec', 'setAction', 'checkout', { step: 1 })

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
