### ISSUE TITLE
Placement of export default

### ISSUE THREAD

**Issue by Cobwebster** [sergiodxa/next-ga#44]
This is a pretty basic question and I apologise in advance,

I'm just using a normal nextjs setup with a index.js and no fancy higher order components etc... Can I just export my index.js export default withGA("UA-xxxxxxxxx-1", Router)(Index);

like so and have it work on all pages? Or do I need some kind of better setup to achieve that?

**Comment by mcb-11561** [comment]
I'm in the same place

Bump

**Comment by Cobwebster** [comment]
> I'm in the same place
> 
> Bump

For now I just put this inside my Nav bar that hits every page

```
  componentDidMount() {
    ReactGA.initialize('UA-CODE-2')
    ReactGA.pageview(document.location.pathname)
  }
```

Works fine

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics
