### ISSUE TITLE
question: how is this different from official example?

### ISSUE THREAD

**Issue by dharmeshkakadia** [sergiodxa/next-ga#7]
Sorry, if its naive question, I am trying to integrate GA with my nextjs app and dont really understand if I should be using [official example](https://github.com/zeit/next.js/tree/canary/examples/with-google-analytics) or this one. 

Is your repo just extracting all the required code to make it work in a reusable HOC or there are more differences ?

**Comment by sergiodxa** [comment]
The examples loads Google Tag Manager and manually set everything.

This packages uses react-ga and wrap it in a HOC for Next.js `pages/_app.js` to be used just passing the GA Tracking ID.
